name: CI Test

on:
  workflow_dispatch:
  
  pull_request:
    branches: [main]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run sample script
        run: echo Hello, world

  build:
    name: Generate App Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Bundle 'release' with Gradle
        run: ./gradlew bundleRelease

      # Add the following steps to send an email when the workflow is finished
      - name: Send email on success
        if: success()
        run: |
          curl --url 'https://api.sendmail.io/v1/email' \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "to": "${{ github.actor }}@users.noreply.github.com",
              "from": "${{ github.actor }}@users.noreply.github.com",
              "subject": "CI/CD Pipeline Finished",
              "text": "Email content for success"
            }'

      - name: Send email on failure
        if: failure()
        run: |
          curl --url 'https://api.sendmail.io/v1/email' \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "to": "${{ github.actor }}@users.noreply.github.com",
              "from": "${{ github.actor }}@users.noreply.github.com",
              "subject": "CI/CD Pipeline Failed",
              "text": "Email content for failure"
            }'
